version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: projet_mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_db
      MYSQL_USER: user_projet
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: projet_backend
    ports:
      - "7000:7000"
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=projet_db
      - DB_USER=user_projet
      - DB_PASSWORD=password123
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  db_data:
